export type DemoProject = {
  slug: string;
  title: string;
  mark: string;
  location: string;
  category: string;
  tagline: string;
  description: string;
  heroKicker: string;
  primaryAction: string;
  visualWord: string;
  theme: {
    canvas: string;
    surface: string;
    text: string;
    muted: string;
    accent: string;
    accent2: string;
  };
  navigation: { slug: string; label: string }[];
  offers: { title: string; description: string; price: string; image?: string; gallery?: {src:string;alt:string}[] }[];
  storyTitle: string;
  story: string;
  highlights: string[];
  stats: { value: string; label: string }[];
  contactPrompt: string;
};

export const demoProjects: DemoProject[] = [
  {
    slug: 'daniels-barber',
    title: 'Daniel’s Barber',
    mark: 'DB',
    location: 'Lavras · MG',
    category: 'Barbearia contemporânea',
    tagline: 'Seu estilo. Nossa assinatura.',
    description: 'Cortes precisos, atendimento sem pressa e uma experiência pensada para quem entende que presença também se constrói nos detalhes.',
    heroKicker: 'Desde 2019 · tradição em movimento',
    primaryAction: 'Agendar horário',
    visualWord: 'PRECISÃO',
    theme: {
      canvas: '#08090b',
      surface: '#121418',
      text: '#f5f1e8',
      muted: '#98958d',
      accent: '#e39a3b',
      accent2: '#7a3f16',
    },
    navigation: [
      { slug: 'inicio', label: 'Início' },
      { slug: 'agendamento', label: 'Agendamento' },
      { slug: 'barbearia', label: 'A barbearia' },
      { slug: 'contato', label: 'Contato' },
    ],
    offers: [
      { title: 'Corte assinatura', description: 'Consultoria de estilo, corte e finalização.', price: 'R$ 55' },
      { title: 'Barba clássica', description: 'Toalha quente, desenho e hidratação.', price: 'R$ 45' },
      { title: 'Experiência completa', description: 'Cabelo, barba e acabamento premium.', price: 'R$ 90' },
      { title: 'Pezinho & acabamento', description: 'Manutenção rápida entre os cortes.', price: 'R$ 25' },
    ],
    storyTitle: 'Técnica de ontem. Atitude de agora.',
    story: 'A Daniel’s nasceu para resgatar o cuidado das barbearias clássicas sem abrir mão de uma leitura atual de estilo. Cada atendimento começa com uma conversa e termina com um corte que faz sentido para a rotina de cada cliente.',
    highlights: ['Diagnóstico de estilo', 'Produtos profissionais', 'Horário reservado', 'Ambiente autoral'],
    stats: [
      { value: '7+', label: 'anos de história' },
      { value: '4,9', label: 'avaliação média' },
      { value: '2,4k', label: 'clientes atendidos' },
    ],
    contactPrompt: 'Reserve seu horário e descubra uma barbearia feita no seu ritmo.',
  },
  {
    slug: 'wl-streetwear',
    title: 'WL Streetwear',
    mark: 'WL',
    location: 'Lavras · MG',
    category: 'Streetwear & e-commerce',
    tagline: 'Streetwear com assinatura.',
    description: 'Uma loja urbana completa com coleção autoral, páginas de produto, sacola, checkout, conta de cliente e gestão do catálogo.',
    heroKicker: 'Drop 01 · edição de estreia',
    primaryAction: 'Explorar coleção',
    visualWord: 'PRESENÇA',
    theme: {
      canvas: '#050811',
      surface: '#101d34',
      text: '#f4f7f0',
      muted: '#a6b4cc',
      accent: '#4ed8ff',
      accent2: '#2547f5',
    },
    navigation: [
      { slug: 'inicio', label: 'Início' },
      { slug: 'colecao', label: 'Coleção' },
      { slug: 'produtos', label: 'Produtos' },
      { slug: 'gerencia', label: 'Gerência' },
    ],
    offers: [
      { title: 'Camiseta WL Signature', description: 'Shape amplo e gráfico autoral da coleção de estreia.', price: 'R$ 99' },
      { title: 'Moletom Charcoal', description: 'Moletom encorpado com acabamento urbano.', price: 'R$ 219' },
      { title: 'Short Utility', description: 'Modelagem funcional para acompanhar a rotina.', price: 'R$ 149' },
      { title: 'Óculos Tech Shield', description: 'Acessório de presença com estética futurista.', price: 'R$ 129' },
    ],
    storyTitle: 'Sem regras. Só presença.',
    story: 'A WL Streetwear nasceu para reunir shapes bem resolvidos, gráficos autorais e uma experiência de compra direta, do primeiro contato com o drop até o checkout.',
    highlights: ['Coleção completa', 'Conta de cliente', 'Checkout integrado', 'Gestão do catálogo'],
    stats: [
      { value: '18', label: 'peças no catálogo' },
      { value: '5', label: 'categorias' },
      { value: '100%', label: 'experiência responsiva' },
    ],
    contactPrompt: 'Conheça o drop e encontre as peças que combinam com a sua presença.',
  },
  {
    slug: 'casa-dos-fios',
    title: 'Mundix Aviamentos',
    mark: 'M',
    location: 'Brasil · envio nacional',
    category: 'Fios, linhas & criatividade',
    tagline: 'Cores que inspiram novas histórias.',
    description: 'Um universo de texturas e tonalidades selecionadas para transformar ideias em peças únicas — do primeiro ponto ao acabamento.',
    heroKicker: 'Mais de 180 cores para criar sem limites',
    primaryAction: 'Ver catálogo',
    visualWord: 'TEXTURA',
    theme: {
      canvas: '#fbf4ea',
      surface: '#efe4d6',
      text: '#30231e',
      muted: '#7b6960',
      accent: '#c95072',
      accent2: '#e5a9b8',
    },
    navigation: [
      { slug: 'inicio', label: 'Início' },
      { slug: 'produtos', label: 'Produtos' },
      { slug: 'categorias', label: 'Categorias' },
      { slug: 'carrinho', label: 'Carrinho' },
    ],
    offers: [
      { title: 'Anne 500m', description: '100% algodão mercerizado, brilho e excelente rendimento.', price: 'A partir de R$ 18,90', image: '/demos/products/anne.webp' },
      { title: 'Barroco Maxcolor', description: 'Cores intensas e toque macio para decoração.', price: 'A partir de R$ 24,90', image: '/demos/products/barroco.webp' },
      { title: 'Amigurumi Chenille', description: 'Volume aveludado para peças macias e expressivas.', price: 'A partir de R$ 21,50', image: '/demos/products/amigurumi.webp' },
      { title: 'Fio Náutico 3mm', description: 'Estrutura firme para bolsas, cestos e acessórios.', price: 'A partir de R$ 29,90', image: '/demos/products/nautico.webp' },
    ],
    storyTitle: 'Cada cor abre uma possibilidade.',
    story: 'A Casa dos Fios nasceu do encontro entre técnica e afeto. Nossa curadoria aproxima artesãs, criadores e marcas de matérias-primas bonitas, consistentes e agradáveis de trabalhar.',
    highlights: ['Paleta com 180+ cores', 'Lotes identificados', 'Envio para todo o Brasil', 'Atendimento especializado'],
    stats: [
      { value: '180+', label: 'cores disponíveis' },
      { value: '24h', label: 'para postagem' },
      { value: '12k', label: 'novelos enviados' },
    ],
    contactPrompt: 'Conte o que você quer criar. A gente ajuda a encontrar o fio certo.',
  },
  {
    slug: 'pizza-lavras',
    title: 'Pizza Lavras',
    mark: 'PL',
    location: 'Lavras · MG',
    category: 'Pizzaria & delivery',
    tagline: 'A noite pede pizza. A sua pede sabor.',
    description: 'Massa de fermentação lenta, ingredientes de verdade e combinações que chegam quentes para reunir todo mundo ao redor da mesa.',
    heroKicker: 'Forno aceso · pedidos até 23h30',
    primaryAction: 'Abrir cardápio',
    visualWord: 'FORNO',
    theme: {
      canvas: '#2b0807',
      surface: '#3a0e0a',
      text: '#fff3dc',
      muted: '#d3ab91',
      accent: '#ffb000',
      accent2: '#bf321d',
    },
    navigation: [
      { slug: 'inicio', label: 'Início' },
      { slug: 'cardapio', label: 'Cardápio' },
      { slug: 'combos', label: 'Combos' },
      { slug: 'contato', label: 'Contato' },
    ],
    offers: [
      { title: 'Calabresa', description: 'Muçarela, calabresa fatiada, cebola e orégano.', price: 'A partir de R$ 48', image: '/demos/products/pizza-calabresa.jpg' },
      { title: 'Frango com Catupiry', description: 'Frango temperado, catupiry, milho e orégano.', price: 'A partir de R$ 52', image: '/demos/products/pizza-frango.jpg' },
      { title: 'Quatro Queijos', description: 'Muçarela, gorgonzola, parmesão e requeijão cremoso.', price: 'A partir de R$ 54', image: '/demos/products/pizza-queijos.jpg' },
      { title: 'Chocolate Crocante', description: 'Chocolate ao leite e finalização crocante.', price: 'A partir de R$ 44', image: '/demos/products/pizza-chocolate.jpg' },
    ],
    storyTitle: 'Tempo, fogo e ingredientes honestos.',
    story: 'Nossa massa descansa por 48 horas antes de entrar no forno. É essa espera, somada a produtores locais e receitas equilibradas, que cria uma pizza leve, crocante e cheia de sabor.',
    highlights: ['Fermentação de 48h', 'Molho feito na casa', 'Ingredientes selecionados', 'Entrega acompanhada'],
    stats: [
      { value: '48h', label: 'de fermentação' },
      { value: '25+', label: 'sabores no menu' },
      { value: '35min', label: 'tempo médio' },
    ],
    contactPrompt: 'Escolha o sabor. A gente cuida para chegar perfeito.',
  },
  {
    slug: 'aurele',
    title: 'Auréle',
    mark: 'A',
    location: 'Curadoria · Brasil',
    category: 'Moda feminina contemporânea',
    tagline: 'Vista o que fica na memória.',
    description: 'Uma curadoria de peças femininas desenhadas para atravessar ocasiões, estações e tendências com presença silenciosa.',
    heroKicker: 'Collection 02 · lumière naturelle',
    primaryAction: 'Descobrir coleção',
    visualWord: 'AUREA',
    theme: {
      canvas: '#eee9df',
      surface: '#d9d0c3',
      text: '#211f1c',
      muted: '#706c65',
      accent: '#8e7145',
      accent2: '#b9a990',
    },
    navigation: [
      { slug: 'inicio', label: 'Início' },
      { slug: 'colecao', label: 'Coleção' },
      { slug: 'editorial', label: 'Editorial' },
      { slug: 'contato', label: 'Contato' },
    ],
    offers: [
      { title: 'Vestido Lumière', description: 'Silhueta limpa em tecido acetinado de movimento leve.', price: 'R$ 429', image: '/demos/products/aurele-dress.webp' },
      { title: 'Blusa Camille', description: 'Textura delicada e acabamento de alta costura.', price: 'R$ 289', image: '/demos/products/aurele-blouse.webp' },
      { title: 'Calça Vienne', description: 'Alfaiataria fluida, cintura alta e caimento preciso.', price: 'R$ 349', image: '/demos/products/aurele-pants.webp' },
      { title: 'Bolsa Madeleine', description: 'Estrutura elegante, ferragens foscas e alça removível.', price: 'R$ 579', image: '/demos/products/aurele-bag.webp' },
    ],
    storyTitle: 'Menos ruído. Mais intenção.',
    story: 'A Aurea nasce de uma ideia simples: vestir pode ser um gesto de clareza. Escolhemos tecidos, cortes e acabamentos que valorizam a mulher e continuam relevantes muito além de uma temporada.',
    highlights: ['Curadoria em pequenas séries', 'Tecidos de origem rastreável', 'Modelagem autoral', 'Embalagem premium'],
    stats: [
      { value: '02', label: 'coleções por ano' },
      { value: '18', label: 'peças essenciais' },
      { value: '100%', label: 'curadoria autoral' },
    ],
    contactPrompt: 'Descubra uma curadoria pensada para o seu ritmo e a sua presença.',
  },
  {
    slug: 'hamburgueria-do-gordao',
    title: 'Hamburgueria Na Brasa',
    mark: 'HG',
    location: 'Lavras · MG',
    category: 'Smash, artesanal & delivery',
    tagline: 'Fome de verdade pede um burger de respeito.',
    description: 'Carne na chapa, queijo derretendo e molhos feitos na casa. Aqui o hambúrguer chega sem frescura e com sabor até o último pedaço.',
    heroKicker: 'Chapa quente · entrega todos os dias',
    primaryAction: 'Ver cardápio',
    visualWord: 'BRASA',
    theme: {
      canvas: '#090806',
      surface: '#16120c',
      text: '#fff8e8',
      muted: '#b5a88c',
      accent: '#ff9d00',
      accent2: '#8f2c09',
    },
    navigation: [
      { slug: 'inicio', label: 'Início' },
      { slug: 'cardapio', label: 'Cardápio' },
      { slug: 'combos', label: 'Combos' },
      { slug: 'contato', label: 'Contato' },
    ],
    offers: [
      { title: 'Clássico do Gordão', description: 'Carne, queijo, salada fresca e molho da casa.', price: 'R$ 29', image: '/demos/products/burger-classic.webp' },
      { title: 'Bacon Supremo', description: 'Burger, cheddar, bacon crocante e barbecue.', price: 'R$ 37', image: '/demos/products/burger-bacon.webp' },
      { title: 'Defumado Artesanal', description: 'Blend de 160g, queijo prato e maionese defumada.', price: 'R$ 42', image: '/demos/products/burger-defumado.webp' },
      { title: 'Costela Especial', description: 'Burger de costela, cebola caramelizada e cheddar.', price: 'R$ 45', image: '/demos/products/burger-costela.webp' },
    ],
    storyTitle: 'A chapa é o nosso palco.',
    story: 'A gente acredita em hambúrguer bem executado: blend fresco, pão macio, ponto certo e equilíbrio em cada camada. Sem atalhos, com muita personalidade e aquele exagero que vale a pena.',
    highlights: ['Blend moído diariamente', 'Molhos da casa', 'Pão selado na manteiga', 'Embalagem térmica'],
    stats: [
      { value: '160g', label: 'de carne no artesanal' },
      { value: '11', label: 'burgers autorais' },
      { value: '4,8', label: 'avaliação média' },
    ],
    contactPrompt: 'Sua fome já escolheu. Agora é só chamar.',
  },
  {
    slug: 'serra-alta-imoveis',
    title: 'Serra Alta Imóveis',
    mark: 'SA',
    location: 'Lavras & região',
    category: 'Imóveis selecionados',
    tagline: 'Imóveis selecionados em Lavras.',
    description: 'Imóveis escolhidos com critério, leitura de mercado e acompanhamento próximo para você decidir com segurança.',
    heroKicker: 'Comprar · vender · investir',
    primaryAction: 'Explorar imóveis',
    visualWord: 'MORAR',
    theme: {
      canvas: '#0a1a22',
      surface: '#102b34',
      text: '#eef7f4',
      muted: '#9bb0ae',
      accent: '#d6b879',
      accent2: '#315d60',
    },
    navigation: [
      { slug: 'inicio', label: 'Início' },
      { slug: 'imoveis', label: 'Imóveis' },
      { slug: 'sobre', label: 'Sobre' },
      { slug: 'contato', label: 'Contato' },
    ],
    offers: [
      { title: 'Casa · Jardim Europa', description: '3 suítes, área gourmet e arquitetura contemporânea.', price: 'R$ 1.280.000', image:'/photos/properties/house-1.jpg', gallery:[{src:'/photos/properties/house-1.jpg',alt:'Casa contemporânea com piscina e gramado'},{src:'/photos/properties/house-2.jpg',alt:'Referência de sala de estar contemporânea'},{src:'/photos/properties/house-3.jpg',alt:'Referência de fachada de vidro e área externa'}] },
      { title: 'Apartamento · Centro', description: '2 quartos, vista aberta e 2 vagas de garagem.', price: 'R$ 480.000', image:'/photos/properties/apartment-1.jpg', gallery:[{src:'/photos/properties/apartment-1.jpg',alt:'Sala integrada de apartamento'},{src:'/photos/properties/apartment-2.jpg',alt:'Referência de quarto de apartamento'},{src:'/photos/properties/apartment-3.jpg',alt:'Referência de cozinha contemporânea'}] },
      { title: 'Chácara · Zona Norte', description: 'Área verde, piscina e acesso asfaltado.', price: 'R$ 760.000', image:'/photos/properties/country-1.jpg', gallery:[{src:'/photos/properties/country-1.jpg',alt:'Casa de campo e jardim'},{src:'/photos/properties/country-2.jpg',alt:'Referência de piscina e gazebo em jardim tropical'},{src:'/photos/properties/country-3.jpg',alt:'Referência de jardim arborizado de casa de campo'}] },
      { title: 'Lote · Condomínio Alto', description: '420 m², topografia suave e vista permanente.', price: 'R$ 295.000', image:'/photos/properties/land-1.jpg', gallery:[{src:'/photos/properties/land-1.jpg',alt:'Terreno urbano vazio — imagem ilustrativa'},{src:'/photos/properties/land-2.jpg',alt:'Referência de lote urbano vazio cercado'},{src:'/photos/properties/land-3.jpg',alt:'Referência de vista aérea de terreno sem construções'}] },
    ],
    storyTitle: 'Escuta antes da visita. Critério antes da escolha.',
    story: 'A Serra Alta combina conhecimento local com uma seleção rigorosa de imóveis. Nosso trabalho começa entendendo o momento de cada cliente e só termina quando a decisão realmente faz sentido.',
    highlights: ['Curadoria personalizada', 'Análise documental', 'Visitas acompanhadas', 'Negociação transparente'],
    stats: [
      { value: '92%', label: 'clientes por indicação' },
      { value: '8 anos', label: 'de mercado local' },
      { value: '74', label: 'imóveis selecionados' },
    ],
    contactPrompt: 'Conte como você quer viver. A gente encontra os lugares que combinam.',
  },
  {
    slug: 'orale-odontologia',
    title: 'Oracle Odontologia',
    mark: 'O',
    location: 'Lavras · MG',
    category: 'Odontologia integrada',
    tagline: 'Odontologia completa para cuidar bem de você.',
    description: 'Prevenção, estética, implantes e ortodontia em um só lugar, com avaliação individual e planejamento transparente.',
    heroKicker: 'Clínica odontológica em Lavras',
    primaryAction: 'Agendar avaliação',
    visualWord: 'SORRIR',
    theme: {
      canvas: '#edf6f4',
      surface: '#dcebe7',
      text: '#173b3a',
      muted: '#607d7b',
      accent: '#2d9f96',
      accent2: '#a8d7d0',
    },
    navigation: [
      { slug: 'inicio', label: 'Início' },
      { slug: 'tratamentos', label: 'Tratamentos' },
      { slug: 'equipe', label: 'Equipe' },
      { slug: 'contato', label: 'Contato' },
    ],
    offers: [
      { title: 'Clínica preventiva', description: 'Avaliação, limpeza e acompanhamento periódico para manter sua saúde bucal em dia.', price: 'Agende sua avaliação', image: '/photos/dental/prevencao.jpg' },
      { title: 'Estética do sorriso', description: 'Clareamento e facetas com indicação responsável e planejamento digital.', price: 'Plano personalizado', image: '/photos/dental/estetica.jpg' },
      { title: 'Implantodontia', description: 'Reabilitação planejada com segurança, da avaliação ao acompanhamento pós-operatório.', price: 'Consulta inicial', image: '/photos/dental/implante.jpg' },
      { title: 'Ortodontia', description: 'Aparelhos e alinhadores indicados para as necessidades de cada paciente.', price: 'Diagnóstico completo', image: '/photos/dental/ortodontia.jpg' },
    ],
    storyTitle: 'Planejamento claro. Cuidado em todas as etapas.',
    story: 'Na Oracle, cada atendimento começa com uma avaliação cuidadosa. A equipe explica as possibilidades, apresenta o plano de tratamento e acompanha a evolução de perto, com decisões feitas junto com cada paciente.',
    highlights: ['Planejamento digital', 'Especialistas integrados', 'Ambiente acolhedor', 'Acompanhamento contínuo'],
    stats: [
      { value: '12+', label: 'anos de experiência' },
      { value: '3D', label: 'planejamento digital' },
      { value: '4,9', label: 'avaliação média' },
    ],
    contactPrompt: 'Agende sua avaliação e receba um plano de cuidado feito para você.',
  },
  {
    slug: 'raiz-cafe',
    title: 'Raiz Café',
    mark: 'RC',
    location: 'Lavras · MG',
    category: 'Cafés especiais & cozinha',
    tagline: 'Café com origem. Pausa com significado.',
    description: 'Grãos de pequenos produtores, torra cuidadosa e uma mesa feita para encontros — da primeira extração ao último gole.',
    heroKicker: 'Aberto hoje · 08h às 19h',
    primaryAction: 'Conhecer o menu',
    visualWord: 'ORIGEM',
    theme: {
      canvas: '#21150f',
      surface: '#34231a',
      text: '#f4e7d2',
      muted: '#b7a28f',
      accent: '#d59a54',
      accent2: '#70452a',
    },
    navigation: [
      { slug: 'inicio', label: 'Início' },
      { slug: 'menu', label: 'Menu' },
      { slug: 'historia', label: 'História' },
      { slug: 'contato', label: 'Contato' },
    ],
    offers: [
      { title: 'V60 da Safra', description: 'Extração filtrada com notas da semana.', price: 'R$ 16', image:'/photos/food/v60.jpg' },
      { title: 'Latte Raiz', description: 'Espresso duplo, leite vaporizado e rapadura.', price: 'R$ 18', image:'/photos/food/latte.jpg' },
      { title: 'Pão de Queijo Canastra', description: 'Receita da casa com queijo curado mineiro.', price: 'R$ 12', image:'/photos/food/pao-de-queijo.jpg' },
      { title: 'Brunch do Campo', description: 'Ovos, pão artesanal, frutas e café filtrado.', price: 'R$ 38', image:'/photos/food/brunch.jpg' },
    ],
    storyTitle: 'Do produtor à xícara, sem esconder o caminho.',
    story: 'O Raiz aproxima quem cultiva de quem aprecia. Trabalhamos com cafés rastreáveis da região, torra em pequenos lotes e preparos que respeitam as características de cada safra.',
    highlights: ['Cafés rastreáveis', 'Torra em pequenos lotes', 'Produtores da região', 'Cozinha feita na casa'],
    stats: [
      { value: '6', label: 'fazendas parceiras' },
      { value: '86+', label: 'pontos de qualidade' },
      { value: '100%', label: 'origem rastreada' },
    ],
    contactPrompt: 'Passe para um café, fique pelo tempo que precisar.',
  },
];

export function getDemoProject(slug: string) {
  return demoProjects.find((project) => project.slug === slug);
}
